trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    az pipelines build tag add --build-id $(Build.BuildNumber) --tags FirstTag --detect true --organization https://dev.azure.com/telstradx/
  displayName: 'Run a multi-line script'
