pipeline {
    agent any

    stages {
        stage('Main') {
            steps {
                echo 'Building..'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Dev') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}
